spring.application.name=email-writer
gemini.api.url=${GEMINI_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent}
gemini.api.key=${GEMINI_KEY}
server.port=9191
